Hw02
tru10b/2024-05-otus-spring-Fedotov pull request #2
Opened 2024-06-17 15:01 UTC by tru10b

2024-06-20 16:44 UTC, VladimirMagerov requested changes

2024-06-20 16:44 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/service/ResultServiceImplUnitTest.java
> +    void isShowResultPass() {
Я бы рекомендовал использовать `@Mock`, `@InjectMocks` для управления и инжекта, пример можно посмотреть тут: https://www.baeldung.com/mockito-annotations
Это избавит нас от самостоятельного создания моков, и дополнительного кода.
В обоих тестовых классах.

2024-06-20 16:44 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoIntegrationalTest.java
> +            var out = csvQuestionDao.findAll();
`out` тут лишняя, её присваивать не обязательно.

2024-06-20 16:44 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoIntegrationalTest.java
> +        try {
Для ассёрта исключений лучше использовать специальный `assertThrows`, пример тут: https://stackoverflow.com/questions/40268446/junit-5-how-to-assert-an-exception-is-thrown

2024-06-20 16:44 UTC, VladimirMagerov commented on hw02/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +            for (int i = 0; i < question.answers().size(); i++) {
Было бы правильнее нумеровать варианты ответов для пользователя начиная с 1, а не с 0.

2024-06-21 20:43 UTC, tru10b commented on hw02/src/test/java/ru/otus/hw/service/ResultServiceImplUnitTest.java
> +    void isShowResultPass() {
использовал

2024-06-21 20:43 UTC, tru10b commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoIntegrationalTest.java
> +            var out = csvQuestionDao.findAll();
убрал out

2024-06-21 20:44 UTC, tru10b commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoIntegrationalTest.java
> +        try {
применил

2024-06-21 20:44 UTC, tru10b commented on hw02/src/main/java/ru/otus/hw/service/TestServiceImpl.java
> +            for (int i = 0; i < question.answers().size(); i++) {
исправил нумерацию

2024-06-26 17:39 UTC, VladimirMagerov approved these changes

2024-06-26 17:46 UTC, merged